niryo_one:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Joint Trajetory Controller ---------------------------------------
  niryo_one_follow_joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    gains: 
      joint_1: {p: 200.0, i: 1, d: 20, i_clamp: 1}
      joint_2: {p: 200.0, i: 1, d: 20, i_clamp: 1}
      joint_3: {p: 200.0, i: 1, d: 20, i_clamp: 1}
      joint_4: {p: 200.0, i: 1, d: 20, i_clamp: 1}
      joint_5: {p: 200.0, i: 1, d: 20, i_clamp: 1}
      joint_6: {p: 200.0, i: 1, d: 20, i_clamp: 1}
  
  niryo_one_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint:  joint_1
    pid: {p: 200.0, i: 0.02, d: 20.0}
  
  niryo_one_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint:  joint_2
    pid: {p: 200.0, i: 0.02, d: 20.0}
  
  niryo_one_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint:  joint_3
    pid: {p: 200.0, i: 0.02, d: 20.0}
  
  niryo_one_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint:  joint_4
    pid: {p: 200.0, i: 0.02, d: 20.0}
  
  niryo_one_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint:  joint_5
    pid: {p: 200.0, i: 0.02, d: 20.0}
  
  niryo_one_joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint:  joint_6
    pid: {p: 200.0, i: 0.02, d: 20.0}
