evaluation_labeled_data_path: []
logs_root_path: /home/zhouxian/git/pytorch-dense-correspondence/pdc/logs_proto/cooking
object_id: Broccoli
test:
- Broccoli_1
- Broccoli_2
- Broccoli_3
train:
- Broccoli_1
- Broccoli_2
- Broccoli_3
