evaluation_labeled_data_path: []
logs_root_path: /home/zhouxian/git/pytorch-dense-correspondence/pdc/logs_proto/cooking
object_id: cheese_03
test:
- cheese_03_1
- cheese_03_2
- cheese_03_3
train:
- cheese_03_1
- cheese_03_2
- cheese_03_3
