evaluation_labeled_data_path: []
logs_root_path: /home/zhouxian/git/pytorch-dense-correspondence/pdc/logs_proto/cooking
object_id: Cucumber
test:
- Cucumber_1
- Cucumber_2
- Cucumber_3
train:
- Cucumber_1
- Cucumber_2
- Cucumber_3
