<?xml version="1.0"?>

<!--
    niryo_one.urdf.xacro
    Copyright (C) 2017 Niryo
    All rights reserved.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="niryo_one">

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find niryo_one_description)/urdf/v1/niryo_one.gazebo" />
	
	<!-- Properties -->

    <xacro:property name="distance_origin_shoulder_z" value="0.103" />
    <xacro:property name="distance_shoulder_arm_z" value="0.08" />
    <xacro:property name="distance_arm_elbow_x" value="0.21004" />
    <xacro:property name="distance_arm_elbow_y" value="0.0" />
    <xacro:property name="distance_elbow_forearm_x" value="0.037" />
    <xacro:property name="distance_elbow_forearm_y" value="0.032" />
    <xacro:property name="distance_forearm_wrist_z" value="0.180" />
    <xacro:property name="distance_wrist_hand_x" value="0.018" />
    <xacro:property name="distance_wrist_hand_y" value="0" />
    <xacro:property name="distance_hand_tool" value="0.00" />
    <!-- TSR 2018-19-07 Adding info about test spoon-->
    <xacro:property name="spoon_offset_left" value="0.125" />
    <xacro:property name="spoon_offset_up" value="0.0" />
    <xacro:property name="spoon_offset_forward" value="0.031" />
    <!-- TSR 2018-19-07 Adding info about camera -->
    <xacro:property name="camera_width" value="0.01" />
    <xacro:property name="camera_pitch" value="0.3" />
    <xacro:property name="camera_height" value="0.04" />

	
	<xacro:property name="PI" value="3.14159265359" />

    <xacro:property name="limit_low_shoulder_rotation" value="-3.05433" />
    <xacro:property name="limit_up_shoulder_rotation" value="3.05433" />
    <xacro:property name="limit_low_arm_rotation" value="${-PI/2}" />
    <xacro:property name="limit_up_arm_rotation" value="0.628319" />
    <xacro:property name="limit_low_elbow_rotation" value="-1.401" />
    <xacro:property name="limit_up_elbow_rotation" value="0.994838" />
    <xacro:property name="limit_low_forearm_rotation" value="-2.61799" />
    <xacro:property name="limit_up_forearm_rotation" value="2.61799" />
    <xacro:property name="limit_low_wrist_rotation" value="-2.26893" />
    <xacro:property name="limit_up_wrist_rotation" value="2.26893" />
    <xacro:property name="limit_low_hand_rotation" value="-2.57" />
    <xacro:property name="limit_up_hand_rotation" value="2.57" />


	<!-- Links -->

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="ground_link"/>
    <origin xyz="0 0 1.02" rpy="0 0 0" />
  </joint>

    <link name="ground_link"/>

    <link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/collada/base_link.dae" />
			</geometry>
			<material name="">
				<color rgba="0.2 0.6 1 1" />
			</material>
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/stl/base_link.stl" />
            </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 ${distance_origin_shoulder_z/2}" rpy="0 0 0"/>
          <mass value="0.05"/>
          <inertia
            ixx="1e-3" ixy="0.0" ixz="0.0"
            iyy="1e-3" iyz="0.0"
            izz="1e-3"/>
        </inertial>
	</link>

    <link name="shoulder_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/collada/shoulder_link.dae" />
			</geometry>
			<material name="">
				<color rgba="0.8 0.8 0.8 1" />
			</material>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/stl/shoulder_link.stl" />
            </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 ${distance_shoulder_arm_z/2}" rpy="0 0 0"/>
          <mass value="0.05"/>
          <inertia
            ixx="1e-3" ixy="0.0" ixz="0.0"
            iyy="1e-3" iyz="0.0"
            izz="1e-3"/>
        </inertial>
	</link>

    <link name="arm_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/collada/arm_link.dae" />
			</geometry>
			<material name="">
				<color rgba="0.2 0.6 1 1" />
			</material>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/stl/arm_link.stl" />
            </geometry>
        </collision>
        <inertial>
          <origin xyz="${distance_arm_elbow_x/2} ${distance_arm_elbow_y/2} 0" rpy="0 0 0"/>
          <mass value="0.05"/>
          <inertia
            ixx="1e-3" ixy="0.0" ixz="0.0"
            iyy="1e-3" iyz="0.0"
            izz="1e-3"/>
        </inertial>
	</link>
	
    <link name="elbow_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <!--	<box size="0.1 0.1 0.048"/> -->
                <mesh filename="package://niryo_one_description/meshes/v1/collada/elbow_link.dae" /> 
			</geometry>
			<material name="">
				<color rgba="0.8 0.8 0.8 1" />
			</material>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/stl/elbow_link.stl" />
            </geometry>
        </collision>
        <inertial>
          <origin xyz="${distance_elbow_forearm_x/2} ${distance_elbow_forearm_y/2} 0" rpy="0 0 0"/>
          <mass value="0.05"/>
          <inertia
            ixx="1e-3" ixy="0.0" ixz="0.0"
            iyy="1e-3" iyz="0.0"
            izz="1e-3"/>
        </inertial>
	</link>

    <link name="forearm_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/collada/forearm_link.dae" />
			</geometry>
			<material name="">
				<color rgba="0.2 0.6 1 1" />
			</material>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/stl/forearm_link.stl" />
            </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 ${distance_forearm_wrist_z/2}" rpy="0 0 0"/>
          <mass value="0.05"/>
          <inertia
            ixx="1e-3" ixy="0.0" ixz="0.0"
            iyy="1e-3" iyz="0.0"
            izz="1e-3"/>
        </inertial>
	</link>

    <link name="wrist_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/collada/wrist_link.dae" />
			</geometry>
			<material name="">
				<color rgba="0.8 0.8 0.8 1" />
			</material>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/stl/wrist_link.stl" />
            </geometry>
        </collision>
        <inertial>
          <origin xyz="${distance_wrist_hand_x/2} ${distance_wrist_hand_y/2} 0" rpy="0 0 0"/>
          <mass value="0.05"/>
          <inertia
            ixx="1e-3" ixy="0.0" ixz="0.0"
            iyy="1e-3" iyz="0.0"
            izz="1e-3"/>
        </inertial>
	</link>
	
    <link name="hand_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/collada/hand_link.dae" />
			</geometry>
			<material name="">
				<color rgba="0.6 0 0 1" />
			</material>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/stl/hand_link.stl" />
            </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.05"/>
          <inertia
            ixx="1e-3" ixy="0.0" ixz="0.0"
            iyy="1e-3" iyz="0.0"
            izz="1e-3"/>
        </inertial>
	</link>
	
    <link name="tool_link">
	</link>
    <link name="spoon_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/stl/spoon.stl" />
			</geometry>
			<material name="">
				<color rgba="0.6 0 0 1" />
			</material>
		</visual>
        <collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/v1/stl/spoon.stl" />
            </geometry>
        </collision>
        <inertial>
          <origin xyz="${-spoon_offset_left} 0 0" rpy="0 0 0"/>
          <mass value="0.05"/>
          <inertia
            ixx="1e-3" ixy="0.0" ixz="0.0"
            iyy="1e-3" iyz="0.0"
            izz="1e-3"/>
        </inertial>
	</link>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_width} ${camera_width} ${camera_width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_width} ${camera_width} ${camera_width}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>

  <link name="camera_link_optical">
  </link>


	<!--Joints -->

    <joint name="ground_joint" type="fixed">
        <parent link="ground_link" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

	<joint name="joint_1" type="revolute">
        <parent link="base_link" />
        <child link="shoulder_link" />
		<origin xyz="0 0 ${distance_origin_shoulder_z}" rpy="0 0 0" />
		<axis xyz="0 0 1" />
		<limit effort="1" velocity="1.0" lower="${limit_low_shoulder_rotation}" upper="${limit_up_shoulder_rotation}" />
	</joint>

	<joint name="joint_2" type="revolute">
        <parent link="shoulder_link" />
        <child link="arm_link" />
        <origin xyz="0 0 ${distance_shoulder_arm_z}" rpy="${PI/2} ${-PI/2} 0" />
		<limit effort="1" velocity="1.0" lower="${limit_low_arm_rotation}" upper="${limit_up_arm_rotation}" />
		<axis xyz="0 0 1" />
	</joint>

	<joint name="joint_3" type="revolute">
        <parent link="arm_link" />
        <child link="elbow_link" />
        <origin xyz="${distance_arm_elbow_x} ${distance_arm_elbow_y} 0" rpy="0 0 ${-PI/2}" />
		<limit effort="1" velocity="1.0" lower="${limit_low_elbow_rotation}" upper="${limit_up_elbow_rotation}" />
		<axis xyz="0 0 1" />	
	</joint>

	<joint name="joint_4" type="revolute">
        <parent link="elbow_link" />
        <child link="forearm_link" />
        <origin xyz="${distance_elbow_forearm_x} ${distance_elbow_forearm_y} 0" rpy="0 ${PI/2} 0" />
		<limit effort="1" velocity="1.0" lower="${limit_low_forearm_rotation}" upper="${limit_up_forearm_rotation}" />
		<axis xyz="0 0 1" />
	</joint>

	<joint name="joint_5" type="revolute">
        <parent link="forearm_link" />
        <child link="wrist_link" />
		<origin xyz="0 0 ${distance_forearm_wrist_z}" rpy="0 ${-PI/2} 0" />
		<limit effort="1" velocity="1.0" lower="${limit_low_wrist_rotation}" upper="${limit_up_wrist_rotation}" />
		<axis xyz="0 0 1" />
	</joint>

	<joint name="joint_6" type="revolute">
        <parent link="wrist_link" />
        <child link="hand_link" />
        <origin xyz="${distance_wrist_hand_x} ${distance_wrist_hand_y} 0" rpy="0 ${PI/2} 0" />
		<limit effort="1" velocity="1.0" lower="${limit_low_hand_rotation}" upper="${limit_up_hand_rotation}" />
		<axis xyz="0 0 1" />
	</joint>

	<joint name="hand_tool_joint" type="fixed">
        <parent link="hand_link" />
        <child link="tool_link" />
        <origin xyz="0 0 ${distance_hand_tool}" rpy="${-PI/2} ${-PI/2} 0" />
        </joint>

	<joint name="camera_link_joint" type="fixed">
        <parent link="hand_link" />
        <child link="camera_link" />
        <origin xyz="0.01 ${camera_height} ${spoon_offset_forward}" rpy="${-PI/2} 0 ${-camera_pitch}" />
        </joint>

	<joint name="hand_spoon_joint" type="fixed">
        <parent link="hand_link" />
        <child link="spoon_link" />
        <origin xyz="${spoon_offset_left} ${spoon_offset_up} ${spoon_offset_forward}" rpy="0 0 0" />
	</joint>

<!-- Actuators -->

<transmission name="transmission_1">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint_1">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="stepper_motor_1">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
<transmission name="transmission_2">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint_2">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="stepper_motor_2">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
<transmission name="transmission_3">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint_3">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="stepper_motor_3">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
<transmission name="transmission_4">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint_4">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="stepper_motor_4">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
<transmission name="transmission_5">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint_5">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="stepper_motor_5">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
<transmission name="transmission_6">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="joint_6">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="stepper_motor_6">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
</robot>
